-- This file is NOT a ready-to-run SQL patch.
-- It previously contained accidental npm CLI output instead of `prisma migrate diff` results.
--
-- Generate a real SQL script (without applying it yet):
--
--   cd frontend
--   npx prisma migrate diff \
--     --from-url "$DATABASE_URL" \
--     --to-schema-datamodel prisma/schema.prisma \
--     --script > ../patch.sql
--
-- Run the command from `frontend/` so the project's Prisma version is used.
--
-- Supabase's UI "migrations" count is unrelated to Prisma's `_prisma_migrations` table.
